FROM node:17 AS build
WORKDIR /build

COPY src/status-map-ui/package*.json ./
RUN npm ci

COPY src/status-map-ui .
RUN NODE_OPTIONS=--openssl-legacy-provider \
    npm run build

FROM nginx:1.21.6
WORKDIR /var/www/html
COPY src/status-map-ui/default.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /build/build/ /usr/share/nginx/html

